networks:
  proxy_sql-network:
    external: true
  proxy_primary-network:
    external: true

services:
  gol-service:
    image: nginx:alpine
    container_name: gol
    hostname: gol
    networks:
      - proxy_sql-network
      - proxy_primary-network
    volumes:
      - /src/gol/web:/usr/share/nginx/html:ro
    restart: unless-stopped
